/* Generated by Yosys 0.29+44 (git sha1 88c849d11, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "memory.v:1.1-15.10" *)
module memory(clk, addr, din, dout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "memory.v:6.7-6.11" *)
  input addr;
  wire addr;
  (* src = "memory.v:6.12-6.15" *)
  input clk;
  wire clk;
  (* src = "memory.v:7.22-7.25" *)
  input din;
  wire din;
  (* src = "memory.v:8.27-8.31" *)
  output dout;
  wire dout;
  wire \mem[0] ;
  wire \mem[1] ;
  INVX1 _08_ (
    .A(\mem[0] ),
    .Y(_06_)
  );
  INVX1 _09_ (
    .A(\mem[1] ),
    .Y(_07_)
  );
  NAND2X1 _10_ (
    .A(\mem[1] ),
    .B(addr),
    .Y(_03_)
  );
  OAI21X1 _11_ (
    .A(_06_),
    .B(addr),
    .C(_03_),
    .Y(_00_)
  );
  NAND2X1 _12_ (
    .A(addr),
    .B(din),
    .Y(_04_)
  );
  OAI21X1 _13_ (
    .A(_07_),
    .B(addr),
    .C(_04_),
    .Y(_02_)
  );
  NOR2X1 _14_ (
    .A(addr),
    .B(din),
    .Y(_05_)
  );
  AOI21X1 _15_ (
    .A(_06_),
    .B(addr),
    .C(_05_),
    .Y(_01_)
  );
  DFFPOSX1 _16_ (
    .CLK(clk),
    .D(_01_),
    .Q(\mem[0] )
  );
  DFFPOSX1 _17_ (
    .CLK(clk),
    .D(_00_),
    .Q(dout)
  );
  DFFPOSX1 _18_ (
    .CLK(clk),
    .D(_02_),
    .Q(\mem[1] )
  );
endmodule
