#!/bin/tcsh -f

echo "\t##############################################################"
echo "\t##############################################################"
echo "\t############		VSDSYNTH		 #############"
echo "\t############  A SHELL SCRIPT TO PARSE INPUT CSV  #############"
echo "\t##############################################################"
echo "\t##############################################################"

echo "\tExecuting vsdsynth command"
echo
echo "****************************************************************************************************"
echo "\t This UI takes RTL Netlist and SDC constraints as input,"
echo "\t and will generate synthesized netlist & pre-layout timng report as output. Uses yosys "
echo "\t open-source tool for synthesis & Opentimer to generate pre-layout timing reports."
echo
echo "\t For queries, drop a mail to kunalpghosh@gmail.com"
echo "****************************************************************************************************"
set my_work_directory = `pwd`

#-----------------------------------------------------------#
#--------------------- Tool Activity -----------------------#
#-----------------------------------------------------------#

if ($#argv != 1) then
	echo "You have not provided .csv file, please provide one or reach out to mail-id provided"
	exit 1	
endif

if(! -f $argv[1] || $argv[1] == "-help") then
	if($argv[1] != "-help") then
		echo "ERROR: Cannot find csv file $argv[1], Exiting..."
		exit 1
	else
		echo COMMAND USAGE: ./vsdsynth \<csv file\>
		echo
		echo 		"where <csv file> consists of 2 columns, where 1st column is CASE SENSITIVE, has below keywords->"
		echo
		echo 		       "<Design Name> : name of top level module"
		echo
		echo 		  "<Output Directory> : path where you want to dump synthesis script, synthesized netlist & timing reports"
		echo
		echo 		 "<Netlist Directory> : path where RTL netlist is present"
		echo
		echo 		"<Early Library Path> : path of early cell library to be used for STA"
		echo
		echo 		 "<Late Library Path> : path of late cell library to be used for STA"
		echo
		echo 		  "<Constraints File> : .csv file path of constraints to be used for STA"
		echo
		exit 1
	endif
else
	tclsh vsdsynth.tcl $argv[1]
endif
